[package]
name = "geario"
version = "0.1.0"
description = "Async IO stack for the Neton ecosystem, ported from ntex"
keywords = ["network", "async", "io", "io-uring"]
categories = ["network-programming", "asynchronous"]
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
name = "geario"
path = "src/lib.rs"

[lints]
workspace = true

[features]
default = []
trace = []
no-test-logging = []
tokio = ["tok-io"]
compio = ["compio-driver", "compio-runtime"]
simd = ["simdutf8"]
overuse = []

[dependencies]
geario-macros = { workspace = true }
bytes = { workspace = true }
foldhash = { workspace = true }
thiserror = { workspace = true }
bitflags = { workspace = true }
env_logger = { workspace = true }
futures-core = { workspace = true }
hashbrown = { workspace = true, features = ["serde"] }
pin-project-lite = { workspace = true }
atomic-waker = { workspace = true }
async-channel = { workspace = true }
async-task = { workspace = true }
crossbeam-queue = { workspace = true }
crossbeam-channel = { workspace = true }
futures-timer = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["signal"] }
oneshot = { workspace = true }
parking_lot = { workspace = true }
scoped-tls = { workspace = true }
swap-buffer-queue = { workspace = true }
compio-driver = { workspace = true, optional = true }
compio-runtime = { workspace = true, optional = true }
tok-io = { workspace = true, features = ["rt", "net"], optional = true }
log = { workspace = true }
slab = { workspace = true }
serde = { workspace = true }
simdutf8 = { workspace = true, optional = true }
backtrace = { workspace = true }

[target.'cfg(target_family = "unix")'.dependencies]
signal-hook = { workspace = true }

[target.'cfg(target_family = "windows")'.dependencies]
ctrlc = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
async-channel = { workspace = true }
derive_more = { workspace = true, features = ["debug", "display"] }
futures-util = { workspace = true }
oneshot = { workspace = true }
serde_test = { workspace = true }
serde_json = { workspace = true }
