[package]
name = "geario"
version = "0.1.0"
description = "Async IO stack for the Neton ecosystem, ported from ntex"
keywords = ["network", "async", "io", "io-uring"]
categories = ["network-programming", "asynchronous"]
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
name = "geario"
path = "src/lib.rs"

[lints]
workspace = true

[features]
default = []
trace = []
no-test-logging = []
neon-polling = []
neon-uring = []
neon-iocp = []
tokio = ["tok-io"]
compio = ["compio-net", "compio-driver", "compio-runtime", "compio-buf", "compio-io"]
simd = ["simdutf8"]
overuse = []

[dependencies]
geario-macros = { workspace = true }
bytes = { workspace = true }
foldhash = { workspace = true }
thiserror = { workspace = true }
bitflags = { workspace = true }
cfg-if = { workspace = true }
http = { workspace = true }
ntex-polling = { workspace = true }
socket2 = { workspace = true, features = ["all"] }
compio-buf = { workspace = true, optional = true }
compio-io = { workspace = true, optional = true }
compio-net = { workspace = true, optional = true }
env_logger = { workspace = true }
futures-core = { workspace = true }
hashbrown = { workspace = true, features = ["serde"] }
pin-project-lite = { workspace = true }
atomic-waker = { workspace = true }
async-channel = { workspace = true }
async-task = { workspace = true }
crossbeam-queue = { workspace = true }
crossbeam-channel = { workspace = true }
futures-timer = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["signal"] }
oneshot = { workspace = true }
parking_lot = { workspace = true }
scoped-tls = { workspace = true }
swap-buffer-queue = { workspace = true }
compio-driver = { workspace = true, optional = true }
compio-runtime = { workspace = true, optional = true }
tok-io = { workspace = true, features = ["rt", "net"], optional = true }
log = { workspace = true }
slab = { workspace = true }
serde = { workspace = true }
simdutf8 = { workspace = true, optional = true }
backtrace = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
ntex-io-uring = { workspace = true, features = ["direct-syscall"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_WindowsProgramming",
] }

[target.'cfg(target_family = "unix")'.dependencies]
signal-hook = { workspace = true }

[target.'cfg(target_family = "windows")'.dependencies]
ctrlc = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
async-channel = { workspace = true }
derive_more = { workspace = true, features = ["debug", "display"] }
futures-util = { workspace = true }
oneshot = { workspace = true }
serde_test = { workspace = true }
serde_json = { workspace = true }
